name: eigendata-demo
channels:
 - defaults
 - fastai
 - conda-forge
dependencies:
 - python=3.7
 - pandas=1.1.2
 - numpydoc=1.1.0 
 - fastcore=1.3.2
 - nodejs>10.14.0
 - jupyterlab=2.2.6
 - jupyterhub=1.2.2
 - xlrd=1.2.0
 - rapidfuzz=1.4.1
 - missingno=0.4.2 
 - plotly=4.14.1
 - nbgitpuller
 - pip
 - pip:
    - fastdata