#!/bin/bash

# Install a JupyterLab extension for demonstration purposes
jupyter labextension install @molinsp/eigendata --minimize=False

# Setup a workspace
jupyter lab workspaces import workspace.json
